#!/bin/bash
#
# &copy; 2017-2018 Regents of the University of California and the Broad Institute. All rights reserved.
#
# strip off spaces if present
TASKLIB="$(echo -e "${1}" | tr -d '[:space:]')"
INPUT_FILES_DIR="$(echo -e "${2}" | tr -d '[:space:]')"
S3_ROOT="$(echo -e "${3}" | tr -d '[:space:]')"
WORKING_DIR="$(echo -e "${4}" | tr -d '[:space:]')"
EXECUTABLE=$5

#
# assign filenames for STDOUT and STDERR if not already set
#
: ${GP_METADATA_DIR=$WORKING_DIR/.gp_metadata}
: ${STDOUT_FILENAME=stdout.txt}
: ${STDERR_FILENAME=stderr.txt}
: ${EXITCODE_FILENAME=$GP_METADATA_DIR/exit_code.txt}

# we need a no-op default for MOD_LIBS
: ${MOD_LIBS=$GP_METADATA_DIR}
: ${MOD_LIBS_S3=$GP_METADATA_DIR}

cd $LOCAL_DIR$WORKING_DIR

echo "========== DEBUG inside 1st container, runLocal.sh - running module now  ================="

# pull first so that the stderr.txt is not polluted by the output of docker getting the image
docker pull $DOCKER_CONTAINER

# start the container with an endless loop
# copy the desired dirs into it
# run the module command
# copy the contents back out to the local disk

#  --mount type=bind,src={bind_src},dst={bind_dst}

CONTAINER_ID="`docker run -d   --mount type=bind,src=$LOCAL_DIR$GP_METADATA_DIR,dst=$GP_METADATA_DIR --mount type=bind,src=$LOCAL_DIR$TASKLIB,dst=$TASKLIB --mount type=bind,src=$LOCAL_DIR$INPUT_FILES_DIR,dst=$INPUT_FILES_DIR --mount type=bind,src=$LOCAL_DIR$WORKING_DIR,dst=$WORKING_DIR  -t $DOCKER_CONTAINER sleep 1d`"

echo CONTAINER_ID is $CONTAINER_ID

# the MOD_LIBS is handled different so that it gets captured in the saved image
docker exec $CONTAINER_ID mkdir -p $MOD_LIBS
docker cp $LOCAL_DIR$MOD_LIBS/. $CONTAINER_ID:$MOD_LIBS

#
# the actual exec - do we capture stderr here or move it inside of the exec.sh generated by GP
#
echo docker exec -e GP_METADATA_DIR="$GP_METADATA_DIR" -t $CONTAINER_ID sh $EXECUTABLE
docker exec -e GP_METADATA_DIR="$GP_METADATA_DIR" -t $CONTAINER_ID sh $EXECUTABLE >$LOCAL_DIR$GP_METADATA_DIR/$STDOUT_FILENAME 2>$LOCAL_DIR$GP_METADATA_DIR/$STDERR_FILENAME 

echo Module execution complete 
docker stop $CONTAINER_ID
/usr/local/bin/saveContainerInECR.sh




